name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "12.0"
      FLUTTER_VERSION: "3.7.12"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: 'stable'
          cache: true
      - run: flutter pub upgrade
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - name: GIT commit and push docs
        run: |
          git config --global user.name "Micah Teeuws"
          git config --global user.email "username@users.noreply.github.com"
          git add pubspec.yaml pubspec.lock
          git commit -m "update pubspec"
          git push
